HELP_INTRO = "Вас приветствует справка!"
HELP_HELP = "\"--help\" (\"-h\") - вызов справки"
HELP_WIDTH = "\"--width [ширина]\" (\"-w\") - ширина поля в клетках"
HELP_HEIGHT = "\"--height [высота]\" (\"-H\") - высота поля в клетках"
HELP_RANDOM = "\"--randomize\" (\"-r\") - сгенерировать случайное поле"
HELP_CELLSIZE = "\"--cell_size [сторона]\" (\"-c\") - сторона клетки на поле"
HELP_SPEED = "\"--speed [скорость]\" (\"-s\") - скорость смены шагов"
HELP_LINESOFF = "\"--lines_off\" (\"-o\") - выключить линии"
HELP_FROMFILE = "\"--from_file\" (\"-l\") - загрузить из файла"
HELP_MAXGEN = "\"--maxgen [количество]\" (\"-m\") - максимальное количество поколений"

HELP_INFORM = "Чтобы увидеть справку, запустите с аргументом \"--help\""
CONTROL_GUI = "ПРОБЕЛ для паузы, клик для переключения жизни в клетке, S для выхода с сохранением"
CONTROL_CONSOLE = "\"q\" - для выхода, \"s\" - для сохранения, любая другая клавиша - для продолжения"

WELCOME_START = "Добро пожаловать в игру Жизнь "
WELCOME_GUI = WELCOME_START + "(графическая версия)!"
WELCOME_CONSOLE = WELCOME_START + "(консольная версия)!"

SETTINGS_INTRO = "Установлены следующие параметры:"
SETTINGS_WIDTH = "Ширина поля в клетках:"
SETTINGS_HEIGHT = "Высота поля в клетках:"
SETTINGS_SOURCE = "Поле:"
SETTINGS_SOURCE_RANDOM = SETTINGS_SOURCE + " случайное"
SETTINGS_SOURCE_EMPTY = SETTINGS_SOURCE + " пустое"
SETTINGS_CELLSIZE = "Сторона клетки на поле:"
SETTINGS_SPEED = "Скорость смены поколений:"
SETTINGS_LINESOFF = "Линии выключены"
SETTINGS_MAXGEN = "Максимальное количество поколений: "

SAVE = "Куда сохранить? (Оставьте пустым для возврата):"

ERROR = "-- ОШИБКА! -- "
GRID_TOO_BIG = ERROR + "Слишком большое поле, невозможно отобразить!"
SPEED_TOO_BIG = ERROR + "Слишком большая задержка, уменьшите аргумент \"-s\""
